# Generated by Django 4.1.6 on 2023-02-05 22:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Receita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=200)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("salario", "Salário"),
                            ("vale", "Vale"),
                            ("bonus", "Bonus"),
                            ("comissao", "Comissão"),
                            ("freelancer", "Freelancer"),
                            ("extra", "Extra"),
                        ],
                        default="salario",
                        max_length=20,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "forma",
                    models.CharField(
                        choices=[
                            ("dinheiro", "Dinheiro"),
                            ("conta", "Conta"),
                            ("outros", "Outros"),
                        ],
                        default="dinheiro",
                        max_length=20,
                    ),
                ),
                ("data", models.DateField(blank=True, default=datetime.date.today)),
                ("pago", models.BooleanField(default=True)),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DespesaP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=100)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("alimentacao", "Alimentação"),
                            ("moradia", "Moradia"),
                            ("transporte", "Transporte"),
                            ("saude", "Saúde"),
                            ("educacao", "Educação"),
                            ("lazer", "Lazer"),
                            ("extra", "Extra"),
                        ],
                        default="alimentacao",
                        max_length=20,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "forma",
                    models.CharField(
                        choices=[
                            ("debito", "Débito"),
                            ("credito", "Crédito"),
                            ("dinheiro", "Dinheiro"),
                            ("pix", "Pix"),
                            ("transferencia", "Transferência"),
                            ("outras", "Outras"),
                        ],
                        default="dinheiro",
                        max_length=20,
                    ),
                ),
                ("data", models.DateField(blank=True, default=datetime.date.today)),
                ("pago", models.BooleanField(default=True)),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
