# Generated by Django 3.2.17 on 2023-03-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoais', '0002_rename_despesap_despesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=models.CharField(choices=[('1', 'Salário'), ('2', 'Vale'), ('3', 'Bonus'), ('4', 'Comissão'), ('5', 'Freelancer'), ('6', 'Extra')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='receita',
            name='forma',
            field=models.CharField(choices=[('1', 'Dinheiro'), ('2', 'Conta'), ('3', 'Outros')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='receita',
            name='pago',
            field=models.CharField(choices=[('1', 'Pago'), ('2', 'Pago')], default='1', max_length=1),
        ),
    ]
