# Generated by Django 3.2.17 on 2023-03-03 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoais', '0003_auto_20230302_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=models.CharField(choices=[('salario', 'Salário'), ('vale', 'Vale'), ('bonus', 'Bonus'), ('comissao', 'Comissão'), ('freelancer', 'Freelancer'), ('extra', 'Extra')], default='salario', max_length=20),
        ),
        migrations.AlterField(
            model_name='receita',
            name='forma',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('conta', 'Conta'), ('outros', 'Outros')], default='dinheiro', max_length=20),
        ),
        migrations.AlterField(
            model_name='receita',
            name='pago',
            field=models.BooleanField(default=True),
        ),
    ]
