# Generated by Django 3.2.17 on 2023-03-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoais', '0004_auto_20230302_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='pago',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='pago',
        ),
        migrations.AddField(
            model_name='despesa',
            name='status',
            field=models.CharField(choices=[('1', 'Pago'), ('2', 'A Pagar')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='receita',
            name='status',
            field=models.CharField(choices=[('1', 'Pago'), ('2', 'A Pagar')], default='1', max_length=1),
        ),
    ]
