# Generated by Django 3.2.17 on 2023-03-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoais', '0005_auto_20230302_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=models.CharField(choices=[('bonus', 'Bonus'), ('comissao', 'Comissão'), ('extra', 'Extra'), ('freelancer', 'Freelancer'), ('vale', 'Vale'), ('salario', 'Salário')], default='salario', max_length=20),
        ),
        migrations.AlterField(
            model_name='receita',
            name='forma',
            field=models.CharField(choices=[('conta', 'Conta'), ('dinheiro', 'Dinheiro'), ('outros', 'Outros')], default='dinheiro', max_length=20),
        ),
        migrations.AlterField(
            model_name='receita',
            name='status',
            field=models.CharField(choices=[('2', 'A Pagar'), ('1', 'Pago')], default='1', max_length=1),
        ),
    ]
