# Generated by Django 3.2.17 on 2023-03-11 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoais', '0006_auto_20230311_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=models.CharField(choices=[('vale', 'Vale'), ('salario', 'Salário'), ('extra', 'Extra'), ('comissao', 'Comissão'), ('freelance', 'Freelance'), ('bonus', 'Bonus')], default='salario', max_length=20),
        ),
        migrations.AlterField(
            model_name='receita',
            name='forma',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('outros', 'Outros'), ('conta', 'Conta')], default='dinheiro', max_length=20),
        ),
    ]
