# Generated by Django 3.2.17 on 2023-03-23 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoais', '0007_auto_20230311_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=models.CharField(choices=[('salario', 'Salário'), ('vale', 'Vale'), ('bonus', 'Bonus'), ('comissao', 'Comissão'), ('freelance', 'Freelance'), ('extra', 'Extra')], default='salario', max_length=20),
        ),
        migrations.AlterField(
            model_name='receita',
            name='forma',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('conta', 'Conta'), ('outros', 'Outros')], default='dinheiro', max_length=20),
        ),
        migrations.AlterField(
            model_name='receita',
            name='status',
            field=models.CharField(choices=[('1', 'Pago'), ('2', 'A Pagar')], default='1', max_length=1),
        ),
    ]
