# Generated by Django 3.2.17 on 2023-03-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoais', '0008_auto_20230322_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='despesa',
            old_name='status',
            new_name='estado',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='status',
        ),
        migrations.AddField(
            model_name='receita',
            name='estado',
            field=models.CharField(choices=[('1', 'Pago'), ('2', 'A Pagar')], default='1', max_length=1),
        ),
    ]
