# Generated by Django 3.2.17 on 2023-03-24 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoais', '0009_auto_20230323_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='despesa',
            old_name='estado',
            new_name='pago',
        ),
        migrations.RenameField(
            model_name='receita',
            old_name='estado',
            new_name='pago',
        ),
    ]
